"""empty message

Revision ID: 191914b81b03
Revises: 327eb420da75
Create Date: 2015-11-07 10:56:27.297000

"""

# revision identifiers, used by Alembic.
revision = '191914b81b03'
down_revision = '327eb420da75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    ### end Alembic commands ###
