"""empty message

Revision ID: 39f27717adc0
Revises: 4b15c2f73801
Create Date: 2015-11-17 20:47:42.816000

"""

# revision identifiers, used by Alembic.
revision = '39f27717adc0'
down_revision = '4b15c2f73801'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
