"""empty message

Revision ID: 504eae12d5ca
Revises: 46be08c76bdf
Create Date: 2015-11-19 14:52:30.801000

"""

# revision identifiers, used by Alembic.
revision = '504eae12d5ca'
down_revision = '46be08c76bdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
